### ISSUE TITLE
Support profile picture sync

### ISSUE THREAD

**Issue by pravi** [maranda/matrix-bifrost#10]
I heard Matrix supports setting profile pics per group, not sure if xmpp offers muc specific profile pics. One user recently changed their group specific picture based on feedback from users, but their change was not visible on the xmpp side.

**Comment by pravi** [comment]
I found https://xmpp.org/extensions/inbox/muc-avatars.html but it is marked historical

Edit: this seems to be for room avatar not for users

**Comment by maranda** [comment]
There isn't currently an equivalent in XMPP so it can't possibly be implemented in a clean way.
