### ISSUE TITLE
Support SRV records

### ISSUE THREAD

**Issue by ghost** [maranda/matrix-bifrost#12]
I had a bit of a harebrained idea and I have no idea how feasible it would be, but I was thinking that SRV (and maybe TXT) DNS records could be used to simplify interoperability between XMPP and Matrix through bifrost. For example, if someone from Matrix tries to reach out to someone on XMPP, if the XMPP server has the right records setup, it could look like a typical Matrix address ( @user:example.com ) via records something like this:

srv-host=_matrix._tcp.example.com,aria-net.org,443,0,0
srv-host=_matrix._tcp.conference.example.com,aria-net.org,443,0,0

It can tell what XMPP server is wanted via the header. From there, at least from a typical naming scheme for the different XMPP components, bifrost could tell if it's trying to connect to a MUC or a user. Bifrost specific TXT DNS records could be added as well to directly tell bifrost if the address is to a MUC component or not

The reverse will probably depend on bifrost to figure out if a XMPP user is trying to join a channel or message a user purely based on if there's a `#` in front of the address or not. Otherwise, Matrix servers could have SRV records like:

srv-host=_xmpp-server._tcp.example.com,aria-net.org,5269,0,0
srv-host=_xmpps-server._tcp.example.com,aria-net.org,5270,0,0

I have no idea if this would be a worthwhile idea or if it's more trouble than it's worth

**Comment by maranda** [comment]
Bifrost is totally agnostical of the L3/4 layer XMPP wise so no that's not useful. Eveything is handled by the XMPP Server to which Bifrost connects as a component.
