### ISSUE TITLE
Transform automatically non allowed character in Nickname ( Matrix -> XMPP )

### ISSUE THREAD

**Issue by JokerGermany** [maranda/matrix-bifrost#4]
Describe the bug
When a Nickname of Matrix user contains in XMPP not allowed character like emoji, they should be converted automatically to prevent that other xmpp users can't read his messages.

To Reproduce

    Change your Global Nick of a matrix account to something with a emoji in it
    join a XMPP Room
    Send a message
    Some XMPP User won't be able to read the messages.

Expected behavior
Variant 1:
The bridge changed the nickname of the Person automatically.

Variant 2:
The bridge messages the user and tell him, that he need to change his room nickname otherwise not every XMPP User will be able to read his messages.

(Copy of https://github.com/matrix-org/matrix-bifrost/issues/311 )

**Comment by maranda** [comment]
Already fixed in development branch.
