### ISSUE TITLE
Bridge Bot should warn if a messages couldn't be send on the other room.

### ISSUE THREAD

**Issue by JokerGermany** [maranda/matrix-bifrost#5]
I didn't found a way to find out as Matrix user if a XMPP MUC/Matrix Room is set to moderated.
The Messages appear on the Matrix/XMPP side, but they don't appear on the XMPP/Matrix side.
A solution before #3  is released, could be to send a Message in the Room or to the user, that his message couldn't be bridged.

(copy of https://github.com/matrix-org/matrix-bifrost/issues/314 )

**Comment by bleonard252** [comment]
On the Matrix side, this can probably be accomplished currently with `m.room.message` type events with the `m.notice` content type, as this is visually distinct in clients, indicating it wasn't sent by the person but instead by a bot. I don't know if there is an equivalent of this for XMPP messages though.
