### ISSUE TITLE
Remove messages deleted on xmpp side from matrix view as well

### ISSUE THREAD

**Issue by pravi** [maranda/matrix-bifrost#6]
For plumped rooms, at least the admins could remove it manually from the other side, but for gateway room (connected using the pattern address) it cannot even be removed manually. So some explicit images sent in public groups are still there with no way to remove them.

**Comment by maranda** [comment]
@pravi the bridge translates redactions in self-retractions for plumbed rooms or portal rooms (matrix -> xmpp) *and* moderation retractions for gateways (xmpp -> matrix) but it's up for the client to support expecially the former.

**Comment by pravi** [comment]
Thanks for the reply, it turned out some of the xmpp servers hosting mucs were not implementing message moderation.
